from pathlib import Path
import json

items = [
# product and strategy (10)
('office-hours','product-strategy','gstack','https://github.com/garrytan/gstack','Descubrir el problema real mediante preguntas de forcing y reformular la oportunidad.'),
('plan-ceo-review','product-strategy','gstack','https://github.com/garrytan/gstack','Revisar alcance, valor y estrategia desde la perspectiva de producto y dirección.'),
('autoplan','product-strategy','gstack','https://github.com/garrytan/gstack','Encadenar revisión ejecutiva, diseño, ingeniería y DX antes de construir.'),
('to-prd','product-strategy','mattpocock/skills','https://github.com/mattpocock/skills','Convertir una idea en un PRD verificable y accionable.'),
('to-spec','product-strategy','mattpocock/skills','https://github.com/mattpocock/skills','Convertir requisitos ambiguos en una especificación técnica precisa.'),
('domain-modeling','product-strategy','mattpocock/skills','https://github.com/mattpocock/skills','Modelar el dominio, invariantes, entidades y límites del sistema.'),
('grill-me','product-strategy','mattpocock/skills','https://github.com/mattpocock/skills','Someter una propuesta a preguntas adversariales para descubrir riesgos.'),
('research','product-strategy','mattpocock/skills','https://github.com/mattpocock/skills','Investigar con trazabilidad, fuentes y síntesis útil para decisiones.'),
('ai-research-explore','product-strategy','llllllama/rigorpilot-skills','https://github.com/lllllllama/rigorpilot-skills','Explorar un tema complejo y organizar hipótesis y evidencia.'),
('analyze-project','product-strategy','lllllllama/rigorpilot-skills','https://github.com/lllllllama/rigorpilot-skills','Analizar un proyecto existente antes de proponer cambios.'),
# architecture and implementation (10)
('plan-eng-review','architecture','gstack','https://github.com/garrytan/gstack','Fijar arquitectura, flujo de datos, estados, fallos, seguridad y pruebas.'),
('plan-devex-review','architecture','gstack','https://github.com/garrytan/gstack','Diseñar y evaluar la experiencia de desarrollo de extremo a extremo.'),
('implement','architecture','mattpocock/skills','https://github.com/mattpocock/skills','Implementar una especificación con límites de alcance y verificación.'),
('codebase-design','architecture','mattpocock/skills','https://github.com/mattpocock/skills','Diseñar cambios sobre un código existente con comprensión estructural.'),
('improve-codebase-architecture','architecture','mattpocock/skills','https://github.com/mattpocock/skills','Reducir acoplamiento y mejorar la arquitectura sin reescrituras innecesarias.'),
('prisma-database-setup','architecture','prisma/skills','https://github.com/prisma/skills','Diseñar y configurar una base de datos Prisma de forma segura.'),
('prisma-client-api','architecture','prisma/skills','https://github.com/prisma/skills','Usar Prisma Client y sus APIs con patrones mantenibles.'),
('prisma-postgres','architecture','prisma/skills','https://github.com/prisma/skills','Aplicar buenas prácticas para PostgreSQL con Prisma.'),
('supabase','architecture','supabase/agent-skills','https://github.com/supabase/agent-skills','Construir soluciones Supabase con autenticación, datos y RLS.'),
('supabase-postgres-best-practices','architecture','supabase/agent-skills','https://github.com/supabase/agent-skills','Aplicar prácticas de rendimiento, seguridad y diseño en PostgreSQL.'),
# code quality and debugging (10)
('review','code-quality','gstack','https://github.com/garrytan/gstack','Encontrar fallos de producción y huecos de completitud en cambios de código.'),
('investigate','code-quality','gstack','https://github.com/garrytan/gstack','Investigar causas raíz mediante hipótesis y evidencia antes de corregir.'),
('careful','code-quality','gstack','https://github.com/garrytan/gstack','Advertir y bloquear comandos destructivos o de alto riesgo.'),
('freeze','code-quality','gstack','https://github.com/garrytan/gstack','Restringir ediciones a un área de trabajo durante depuración.'),
('guard','code-quality','gstack','https://github.com/garrytan/gstack','Combinar controles de seguridad y bloqueo de alcance para trabajo sensible.'),
('diagnose','code-quality','mattpocock/skills','https://github.com/mattpocock/skills','Diagnosticar errores con un proceso sistemático y reproducible.'),
('diagnosing-bugs','code-quality','mattpocock/skills','https://github.com/mattpocock/skills','Aislar regresiones, causas y correcciones con evidencia.'),
('resolving-merge-conflicts','code-quality','mattpocock/skills','https://github.com/mattpocock/skills','Resolver conflictos de merge preservando intención y pruebas.'),
('tdd','code-quality','mattpocock/skills','https://github.com/mattpocock/skills','Desarrollar con pruebas primero y ciclos cortos de verificación.'),
('request-refactor-plan','code-quality','mattpocock/skills','https://github.com/mattpocock/skills','Preparar un plan de refactorización acotado, medible y reversible.'),
# qa and security (10)
('qa','qa-security','gstack','https://github.com/garrytan/gstack','Probar la aplicación en navegador, corregir fallos y generar regresiones.'),
('qa-only','qa-security','gstack','https://github.com/garrytan/gstack','Realizar una auditoría QA report-only sin modificar código.'),
('cso','qa-security','gstack','https://github.com/garrytan/gstack','Ejecutar revisión OWASP y STRIDE con evidencia y umbral de confianza.'),
('webapp-testing','qa-security','anthropics/skills','https://github.com/anthropics/skills','Probar aplicaciones web con escenarios reproducibles y resultados verificables.'),
('git-guardrails-claude-code','qa-security','mattpocock/skills','https://github.com/mattpocock/skills','Aplicar protecciones para operaciones Git peligrosas.'),
('web-design-guidelines','qa-security','vercel-labs/agent-skills','https://github.com/vercel-labs/agent-skills','Auditar una interfaz según principios web y accesibilidad.'),
('azure-rbac','qa-security','microsoft/azure-skills','https://github.com/microsoft/azure-skills','Diseñar controles de acceso RBAC con mínimo privilegio en Azure.'),
('azure-diagnostics','qa-security','microsoft/azure-skills','https://github.com/microsoft/azure-skills','Diagnosticar incidentes y problemas operativos en Azure.'),
('firebase-basics','qa-security','firebase/agent-skills','https://github.com/firebase/agent-skills','Aplicar fundamentos de Firebase con controles operativos.'),
('full-output-enforcement','qa-security','leonxlnx/taste-skill','https://github.com/leonxlnx/taste-skill','Evitar entregables incompletos mediante validación de salida.'),
# release and operations (10)
('ship','release-ops','gstack','https://github.com/garrytan/gstack','Preparar cambios, ejecutar pruebas, actualizar cobertura y abrir PR.'),
('land-and-deploy','release-ops','gstack','https://github.com/garrytan/gstack','Fusionar, esperar CI/despliegue y verificar salud en producción.'),
('canary','release-ops','gstack','https://github.com/garrytan/gstack','Monitorear errores, rendimiento y fallos después del despliegue.'),
('benchmark','release-ops','gstack','https://github.com/garrytan/gstack','Medir carga, Core Web Vitals y tamaños de recursos antes/después.'),
('document-release','release-ops','gstack','https://github.com/garrytan/gstack','Actualizar documentación para reflejar exactamente lo desplegado.'),
('setup-deploy','release-ops','gstack','https://github.com/garrytan/gstack','Configurar plataforma, URL y comandos para un despliegue repetible.'),
('azure-reliability','release-ops','microsoft/azure-skills','https://github.com/microsoft/azure-skills','Diseñar fiabilidad, redundancia y recuperación para Azure.'),
('azure-cost-optimization','release-ops','microsoft/azure-skills','https://github.com/microsoft/azure-skills','Identificar oportunidades de optimización de costes en Azure.'),
('azure-compute','release-ops','microsoft/azure-skills','https://github.com/microsoft/azure-skills','Elegir y operar recursos de cómputo en Azure.'),
('remotion-best-practices','release-ops','remotion-dev/skills','https://github.com/remotion-dev/skills','Aplicar prácticas sólidas para producir vídeo con Remotion.'),
# design and frontend (10)
('plan-design-review','design-frontend','gstack','https://github.com/garrytan/gstack','Evaluar y elevar una propuesta visual antes de implementarla.'),
('design-consultation','design-frontend','gstack','https://github.com/garrytan/gstack','Crear un sistema de diseño con investigación y riesgos creativos controlados.'),
('design-shotgun','design-frontend','gstack','https://github.com/garrytan/gstack','Explorar variantes visuales y recopilar feedback antes de fijar dirección.'),
('design-html','design-frontend','gstack','https://github.com/garrytan/gstack','Convertir una dirección visual en HTML/CSS dinámico y funcional.'),
('design-review','design-frontend','gstack','https://github.com/garrytan/gstack','Auditar y corregir una interfaz con una mirada de diseñador que programa.'),
('frontend-design','design-frontend','anthropics/skills','https://github.com/anthropics/skills','Diseñar frontend diferenciado y listo para producción.'),
('vercel-composition-patterns','design-frontend','vercel-labs/agent-skills','https://github.com/vercel-labs/agent-skills','Componer componentes React escalables y mantenibles.'),
('vercel-react-best-practices','design-frontend','vercel-labs/agent-skills','https://github.com/vercel-labs/agent-skills','Aplicar rendimiento y buenas prácticas de React y Next.js.'),
('vercel-react-native-skills','design-frontend','vercel-labs/agent-skills','https://github.com/vercel-labs/agent-skills','Construir interfaces React Native con patrones fiables.'),
('ui-ux-pro-max','design-frontend','nextlevelbuilder/ui-ux-pro-max-skill','https://github.com/nextlevelbuilder/ui-ux-pro-max-skill','Diseñar UI/UX con sistema visual, jerarquía y criterios de producto.'),
# documentation and content (10)
('document-generate','docs-content','gstack','https://github.com/garrytan/gstack','Generar documentación completa con enfoque Diátaxis.'),
('make-pdf','docs-content','gstack','https://github.com/garrytan/gstack','Convertir Markdown en documentos publicados con diagramas y layout robusto.'),
('diagram','docs-content','gstack','https://github.com/garrytan/gstack','Crear diagramas editables y renderizables a partir de una descripción.'),
('write-a-skill','docs-content','mattpocock/skills','https://github.com/mattpocock/skills','Crear una skill clara, portable y orientada a resultados.'),
('writing-great-skills','docs-content','mattpocock/skills','https://github.com/mattpocock/skills','Mejorar instrucciones, triggers y disclosure progresivo de una skill.'),
('writing-for-agents','docs-content','mattpocock/skills','https://github.com/mattpocock/skills','Escribir contenido que agentes puedan interpretar y ejecutar.'),
('docx','docs-content','anthropics/skills','https://github.com/anthropics/skills','Crear y editar documentos Word estructurados.'),
('pdf','docs-content','anthropics/skills','https://github.com/anthropics/skills','Leer, generar y verificar documentos PDF.'),
('pptx','docs-content','anthropics/skills','https://github.com/anthropics/skills','Crear presentaciones PowerPoint con estructura y diseño.'),
('xlsx','docs-content','anthropics/skills','https://github.com/anthropics/skills','Crear y analizar hojas de cálculo Excel.'),
# data and cloud (10)
('prisma-cli','data-cloud','prisma/skills','https://github.com/prisma/skills','Usar la CLI de Prisma con migraciones y generación reproducibles.'),
('prisma-compute','data-cloud','prisma/skills','https://github.com/prisma/skills','Aplicar capacidades de cómputo y conexión de Prisma.'),
('prisma-mongodb-upgrade','data-cloud','prisma/skills','https://github.com/prisma/skills','Planificar una actualización de Prisma MongoDB.'),
('prisma-driver-adapter-implementation','data-cloud','prisma/skills','https://github.com/prisma/skills','Implementar adaptadores de drivers para Prisma.'),
('prisma-upgrade-v7','data-cloud','prisma/skills','https://github.com/prisma/skills','Planificar y ejecutar actualizaciones a Prisma v7.'),
('azure-kubernetes','data-cloud','microsoft/azure-skills','https://github.com/microsoft/azure-skills','Diseñar despliegues y operación de Kubernetes en Azure.'),
('azure-messaging','data-cloud','microsoft/azure-skills','https://github.com/microsoft/azure-skills','Diseñar mensajería y comunicación asíncrona en Azure.'),
('azure-quotas','data-cloud','microsoft/azure-skills','https://github.com/microsoft/azure-skills','Gestionar cuotas y límites de servicios Azure.'),
('microsoft-foundry','data-cloud','microsoft/azure-skills','https://github.com/microsoft/azure-skills','Trabajar con capacidades de AI y Foundry de Microsoft.'),
('firebase-data-connect','data-cloud','firebase/agent-skills','https://github.com/firebase/agent-skills','Modelar y conectar datos con Firebase Data Connect.'),
# research, dx, memory (10)
('to-tickets','research-dx','mattpocock/skills','https://github.com/mattpocock/skills','Convertir decisiones y requisitos en tickets ejecutables.'),
('retro','research-dx','gstack','https://github.com/garrytan/gstack','Realizar retrospectivas de ingeniería con tendencias y oportunidades.'),
('learn','research-dx','gstack','https://github.com/garrytan/gstack','Gestionar memoria de proyecto, patrones, errores y preferencias.'),
('devex-review','research-dx','gstack','https://github.com/garrytan/gstack','Auditar la experiencia real de onboarding y desarrollo.'),
('teach','research-dx','mattpocock/skills','https://github.com/mattpocock/skills','Explicar conceptos y guiar aprendizaje mediante ejemplos.'),
('ask-matt','research-dx','mattpocock/skills','https://github.com/mattpocock/skills','Obtener una segunda perspectiva práctica sobre decisiones técnicas.'),
('grill-with-docs','research-dx','mattpocock/skills','https://github.com/mattpocock/skills','Interrogar una decisión usando documentación como evidencia.'),
('zoom-out','research-dx','mattpocock/skills','https://github.com/mattpocock/skills','Ampliar el contexto para evitar optimizaciones locales.'),
('paper-context-resolver','research-dx','lllllllama/rigorpilot-skills','https://github.com/lllllllama/rigorpilot-skills','Resolver contexto y referencias de un paper o investigación.'),
('wayfinder','research-dx','mattpocock/skills','https://github.com/mattpocock/skills','Navegar un código o problema grande hacia el siguiente paso útil.'),
# automation media and integration (10)
('pair-agent','automation-integration','gstack','https://github.com/garrytan/gstack','Coordinar agentes distintos mediante navegador compartido y tokens acotados.'),
('browse','automation-integration','gstack','https://github.com/garrytan/gstack','Dar a un agente acceso controlado a Chromium, clicks y screenshots.'),
('setup-browser-cookies','automation-integration','gstack','https://github.com/garrytan/gstack','Preparar sesiones autenticadas de navegador con importación explícita.'),
('codex','automation-integration','gstack','https://github.com/garrytan/gstack','Solicitar una segunda opinión independiente a otro modelo/agente.'),
('skill-creator','automation-integration','anthropics/skills','https://github.com/anthropics/skills','Crear y empaquetar nuevas skills reutilizables.'),
('ai-video-generation','automation-integration','genmedia-labs/skills','https://github.com/genmedia-labs/skills','Planificar y producir vídeo con modelos generativos.'),
('ai-music','automation-integration','prime-skills/runcomfy-agent-skills','https://github.com/prime-skills/runcomfy-agent-skills','Crear música generativa mediante workflows controlados.'),
('video-edit','automation-integration','prime-skills/runcomfy-agent-skills','https://github.com/prime-skills/runcomfy-agent-skills','Editar vídeo con un flujo de trabajo generativo.'),
('content-strategy','automation-integration','coreyhaines31/marketingskills','https://github.com/coreyhaines31/marketingskills','Diseñar estrategia de contenidos orientada a objetivos.'),
('seo-audit','automation-integration','coreyhaines31/marketingskills','https://github.com/coreyhaines31/marketingskills','Auditar SEO técnico y de contenido.'),
]
assert len(items) == 100, len(items)
entries=[]
for i,(slug,category,source,repo,summary) in enumerate(items,1):
    entries.append({'id':i,'slug':slug,'category':category,'source':source,'repository':repo,'summary':summary,'selection_basis':'Adopción observable en skills.sh o valor operativo probado en el upstream; sujeto a revisión de licencia, seguridad y compatibilidad antes de activar ejecución externa.','status':'reference-only' if 'no disponible' in summary.lower() else 'candidate'})
Path('catalog/skills.json').write_text(json.dumps({'version':'1.0.0','generated_at':'2026-08-26','selection_method':'utility + maturity + ecosystem adoption; no automatic execution of remote skill code','count':100,'skills':entries},ensure_ascii=False,indent=2)+'\n')
print(f'wrote {len(entries)} skills')
